### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by ddavtian** [SungardAS/enhanced-snapshots#116]
Hello,

Is there an article that shows how to update the default SSL cert?

Thanks

**Comment by iradaik** [comment]
Hi @ddavtian, 

Unfortunatly, there is no. If you need to update SSL certificate you can go to /etc/nginx directory and update manually certificate together with the key. After that you will need to restart nginx service

**Comment by ddavtian** [comment]
Thank you @iradaik, I have successfully updated the self signed certificate.
