### ISSUE TITLE
Backup/Restore Question

### ISSUE THREAD

**Issue by ddavtian** [SungardAS/enhanced-snapshots#120]
Hello,

Love the product guys, great work. Just have a simple question. Some of our instances have (2) EBS volumes, would there be an issue in the backup restore process if the EC2 is associated with multiple EBS volumes?

Many Thanks

**Comment by iradaik** [comment]
Hello @ddavtian, 

Thanks a lot for your feedback. As for your question, while backup/restore process system creates temporal volume and attach it to EC2, so as long as the limit of max EBS volumes attached is not reached for the instance you should not have any problems

**Comment by ddavtian** [comment]
@iradaik thank you for your response, during backup/restore is there any downtime from a user's point of view?

**Comment by rabay108** [comment]
@ddavtian there is no downtime between backups and restores. Let us know we can close this issue if all the questions regarding this are answered.
