### ISSUE TITLE
Tasks missing

### ISSUE THREAD

**Issue by mthomassd** [SungardAS/enhanced-snapshots#133]
In the web UI I don't see any tasks:

No tasks to display...

However, they are executing successfully and I can see them in Dynamo:

id	status	tempVolumeIopsPerGb	type	volume	worker	tempVolumeType
cd6b8085-de28-4445-a6eb-07d6950cd6ed	running	0	backup	vol-9abdc839	i-0d9a2b767a362db2f	gp2
69d4ee59-729f-421a-9806-51a1cf8ac06e	queued	0	backup	vol-6aad1997	i-0d9a2b767a362db2f	gp2
9e5a3283-a86c-476c-9b17-96eec80ca834	queued	0	backup	vol-c1c11b64	i-0d9a2b767a362db2f	gp2
ee32a77f-ef4b-4468-8ad8-df972808f3b1	queued	0	backup	vol-12ac18ef	i-0d9a2b767a362db2f	gp2
632ed836-78f6-426e-9ae5-80ef0fce23fd	queued	0	backup	vol-1ed0b856	i-0d9a2b767a362db2f	gp2
af906c90-dcc7-4bdd-a246-d01f0119114a	queued	0	system_backup	system_backup	i-0d9a2b767a362db2f	
c3c8d67a-e002-400a-93b8-c829dab61e02	queued	0	backup	vol-40b2c7e3	i-0d9a2b767a362db2f	gp2
833e50f9-8167-456d-9f62-38ee7f4fa698	queued	0	backup	vol-2617d084	i-0d9a2b767a362db2f	gp2

I am using version 2 from the CloudFormation template in the marketplace.

Any idea on how to fix this?

**Comment by rabay108** [comment]
@mthomassd Our Release 3.0 is in place for a couple of weeks try with it. On the old instance see any volume is running on scheduled with "Yes" in that column.
