### ISSUE TITLE
A backup question

### ISSUE THREAD

**Issue by NareshDealer** [SungardAS/enhanced-snapshots#154]
Hi,
I have been using/testing your application since v1.0 and only comment i have is, its getting better and i m really liking your application.
However, i have a couple of questions to ask.
1. if lets assume, the whole region got down where the application instance is hosted where s3 bucket still exists then how to get the restore the server. I was using v2.0 and when i shutdown the instance and connected a new v3.0 instance to the s3 bucket, i cant see any schedules and cant find a way to restore the backups.
2. if there is a retention policy applied on s3 bucket like moving to glacier after 15 days. will the application be able to restore from glacier.?

**Comment by rabay108** [comment]
@NareshDealer You will be able to migrate the s3 bucket from V2.0 to V3.0; 
From Github the cluster version should be available, though only the single instance version released to Marketplace t this time. 
There is retention policy built in the application and you can set that in the UI. However we are introducing the S3-IA(Infrequent access) in our next version.

**Comment by NareshDealer** [comment]
@rabay108  Thank you for your quick response.
So if i migrate the s3 bucket from v2 to v3, can i still connect v2 and it works as normal.?
Can you please provide some instructions/guidance on how to convert the bucket use it with v3.
question:  for example.. i have taken the application backup 4 days ago and one of the volume backup today. if the application server crash and if i have to rebuild the new version and connect to s3 bucket, will i be able to restore today's backup of the volume.?

**Comment by rabay108** [comment]
@NareshDealer We had some fixes including the cluster and cross AZ replication. Due to that we had to update to the new opendedup SDFS version. Due to that ESS v3.0 does not have backward capability, since SDFS that we use for ESS v3 does not support it. And it does not matter which setup is used (single node or cluster) because for all setups is used one AMI with the same SDFS. Suggestion is to restore those required versions and backup using V3. Going forward we will have some work around planned for this.

**Comment by NareshDealer** [comment]
@rabay108 I have tried to fire up another instance of v2 and connect to same s3 bucket which i was using with previous v2 instance.
When i login to new v2 instance, it doesnt show any backup history or schedules for any volumes. But when i go back to old v2 instance, i can still see them.
Am i missing anything here in this process.?

Thanks.

**Comment by rabay108** [comment]
@NareshDealer How did you stood up the V2 instance? As the Master has been updated with V3 artifacts couple of weeks ago. Is it the same AMI? Intention is to seamlessly migrate V3 to V4.

**Comment by NareshDealer** [comment]
@rabay108 I have used the this "ImageID": "ami-9a5ad28d", which is same used for initial v2. So when we connect to V3 to initial v2 bucket, will it change anything which is causing the new v2 to show the backup history, schedule etc.?

So if it changed something, why can initial v2 still show all schedule and backup history etc.?

Thanks.

**Comment by NareshDealer** [comment]
@rabay108 Any idea for above..?

Thanks.

**Comment by rabay108** [comment]
Using the same bucket will adopt the details as part of the migration process.

**Comment by NareshDealer** [comment]
@rabay108 I did used the same bucket but didnt worked on v2.

Anyway we moved to v3 and started doing our regular tests which all gone through fine including the standing up a new server with connecting to same bucket. But only issue i observed that on new instance, i cant see the schedules on the volume but it will show the backup history and can recover the volume from the backups.

The other question i have is what is the part of dynamo tables in the application... which means one of our test case was to take backup of application on day 1 and take volume backups for 3 days then destroy the current v3 server and build a new one connecting to old v3 bucket which should all the backup history for last 3 days... it passed that but i want to know if we didnt take the backup of application then what are all we are going to loose .?

Also it will be great if there is schedule in place to take the application backup to s3 bucket.


Thanks.

**Comment by rabay108** [comment]
@NareshDealer Thx for the feedback, Are you seeing the schedules showing YES and scheduled jobs no kicking in or schedules themselves missing? DynamoDB tables for V3 10 tables will store the configuration and operational information and you can go and review those tables. Point noted on "Application backup to S3 bucket" @sauravlahiri @nkchitturi

**Comment by NareshDealer** [comment]
@rabay108 The schedules doesnt show YES and not even the schedules.. So i m thinking, the application backup is what its stored under.?

**Comment by NareshDealer** [comment]
@rabay108 I did another test case today.
I created few schedules on volumes and took application backup. 
Shutdown the instance.
delete existing tables in dynamoDB
Create a new instance and connect to existing/old s3 bucket during initial setup.
Check schedules of the volumes.
NONE were available. 

Can you please check and let me know if i m need to do something else to get restores back on new instance.

TIA.

**Comment by rabay108** [comment]
Not sure why the DynamoDB tables were knocked out as they do carry all the metadata, configuration and historic information. The current version does have the components in place for the clustered environment, however not released to the Marketplace unless we complete more testing on that. The full fledged DR features will evolve in the future once we get more feedback from the users.

**Comment by NareshDealer** [comment]
@rabay108 The reason for DynamoDB tables were deleted or why whole above test case is done, to test what if a region is lost where the server is hosted.
If the whole region is lost and we need to restore the volume.. then we should expect everything associated to the region will be lost except S3 bucket.

I observed during the initial configuration of the new instance, the tables from s3 bucket are restored to new tables. 

If this is true then newly created tables should be populated from the backup with all information unless the restore is not restoring.

**Comment by rabay108** [comment]
Soon we will publish information on the High availability features of the V3.0 in clustered environment. The product will evolve further on full fledged DR depending on the usage and inputs from the market users like you. Our product team will take inputs from this discussions for further enhancements. Refer to this article https://blog.sungardas.com/CTOLabs/2015/09/planning-for-failures-with-amazon-dynamodb-2/ for adding the redundancy feature using the DynamoDB available features.
