### ISSUE TITLE
Application Installation steps

### ISSUE THREAD

**Issue by deemanning** [SungardAS/enhanced-snapshots#28]
Within the Readme:

•Install directions seem to be missing some major steps within the staging process under “Quick Start” within the Readme file
-The CFN stack ONLY creates the permission role for “es-admin-role”, the directions states the following: “Once the CloudFormation stack has finished building, go to its Outputs tab at the bottom of the AWS Console. Copy the instance ID (you will need it in a later step) and click the URL, then proceed to Getting Started.” There is nothing within the Outputs tab as stated before the CFN only creates the permission role.  
•Directions does not define what OS the application is supported on (only instance specifications) nor makes any reference to the SnapDirector_AMI JSON script within the project
-Also, do this application requires RDS? If so, what are the staging requirements for RDS?

**Comment by rabay108** [comment]
- The new version needs the es-admin role to launch the AMI and the current cloud formation that you refer invokes the AMI launch. Stay tuned for the fixes on that.
- This has been tested on windows as well and we will document them soon and should support the linux flavors.
- We do't use RDS as DynamoDB is used and the tables are created when the EC2 instance is launched for the first time.

**Comment by deemanning** [comment]
Thanks! I didn't realize that the Instance Launch image was an actual CFN deployment template link. duh.. Thanks for the response, I will stay tuned as to what's to come.

**Comment by drsromero** [comment]
Is the eu-west-1 ami-31714646 available? 

I read "**Note:** Due to feature differences between the AWS regions, the service is not yet available in the following regions: ap-northeast-1, ap-southeast-1, ap-southeast-2, eu-central-1, eu-west-1 and sa-east-1." But it appears in the Launch Stack link, however I get a error deploying the stack: 

> CREATE_FAILED 	AWS::EC2::Instance 	Instance 	API: ec2:RunInstances Not authorized for images: [ami-31714646] 

and I can't find it as public AMI, so I'm not sure if it is available.
Thank you!.

**Comment by rabay108** [comment]
New version will be released soon and will support eu-west-1. Please stay tuned for the announcements.
