### ISSUE TITLE
Performance improvisation needed on the backup and restore processes

### ISSUE THREAD

**Issue by rabay108** [SungardAS/enhanced-snapshots#30]
We have been conducting performance tests with different volumes and currently it is taking 1 hour for around 20GB data. Currently working towards increasing the performance.

**Comment by drsromero** [comment]
I did a volume manual backup for 8Gb Data and it took around 30 minutes. I'm no sure if using S3 Transfer Acceleration could improve the process.
https://docs.aws.amazon.com/es_es/AmazonS3/latest/dev/transfer-acceleration.html

**Comment by rabay108** [comment]
Daniel - Thanks for your feedback. Transfers are taking place with in the same region only between the EC2 and the S3 buckets. So transfer acceleration will not make a difference. In the next version we will have the flexibility to create the temporary volumes with type "io1" and higher iops so the backups will see a huge improvement.
