### ISSUE TITLE
CloudFormation Deployment Fails

### ISSUE THREAD

**Issue by ChrisJones75** [SungardAS/enhanced-snapshots#59]
It appears that the CloudFormation deployment is failing because it's not creating a public IP. We were using the VPC version of the CF template. See below for the failure message from CF:

`16:21:37 UTC-0400	ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	Enhanced-Snapshots-01	Attribute: PublicIp was not found for resource: i-0b22bf1712296faaa. Rollback requested by user.`

**Comment by rabay108** [comment]
@ChrisJones75 Can you let me know which specific CFT was used in the process, as there are 4 of them besides the role creation CFT. Also appreciate if I can get some info on the VPC settings.

**Comment by ChrisJones75** [comment]
The URI of the template is: http://particles-enhanced-snapshots.us-east-1.s3.amazonaws.com/master/particles/cftemplates/sungardas_enhanced_snapshots_with_vpc.template.json

Below is the summary of our VPC (with some ID changes):

> VPC ID: vpc-29b2cccc | Prod-Dedicated
> Network ACL: acl-c4226666
> State: available
> Tenancy: Dedicated
> VPC CIDR: 10.203.0.0/16
> DNS resolution: yes
> DHCP options set: dopt-33654444 | biz.local - AWS
> DNS hostnames: no
> Route table: rtb-09556666
> ClassicLink DNS Support: no

We're running with Direct Connect links to our on prem networks and there are NAT gateways for outbound traffic in the VPC.

**Comment by rabay108** [comment]
@ChrisJones75 As stated on the earlier comment on that issue can you make DNS hostnames: yes instead of no and give it a shot.

**Comment by ChrisJones75** [comment]
Unfortunately I cannot since we're running production resources in this VPC. I can spin up a lab VPC at some point and try it there, but it won't be dedicated tenancy (due to the cost) and I'm not sure when I'll have the availability to do it.

On a positive note, the AMI version seems to be working fine in our environment. We've executed 2 backups successfully and will be testing a restore shortly.

**Comment by ChrisJones75** [comment]
Just to let you know, the restores work as well. This app will definitely suit our backup purposes. Thanks for creating it.

**Comment by rabay108** [comment]
@ChrisJones75 Appreciate using the tool and the feedback. One more clarification I would like to have is did you launch the instance that worked for you from AMI in the same VPC that you have the issue with the CFT?

**Comment by ChrisJones75** [comment]
Yes, the AMI version is in the same VPC that we tried deploying the CFT to.

Additionally, I just tried a CF deployment this morning on a VPC with DNS Hostnames on and got the same rollback. The VPC has dedicated tenancy as well. Here's the summary:

> VPC ID: vpc-bc778888 | NonProd-Dedicated
> Network ACL: acl-9faebbbb
> State: available
> Tenancy: Dedicated
> VPC CIDR: 10.200.0.0/16
> DNS resolution: yes
> DHCP options set: dopt-2c899999 | biz.local - AWS
> DNS hostnames: yes
> Route table: rtb-47fb3333
> ClassicLink DNS Support: no

**Comment by rabay108** [comment]
@ChrisJones75 we tested again with the similar setup. you need to allow Auto-assign Public IP for subnet. AWS VPC => Subnets => select subnet => Subnet Actions => Modify Auto-assign Public IP => Enable. Can you check this setting on your side and circle back to me.

**Comment by rabay108** [comment]
The new version V2.0 is released and as stated in the previous comment check the VPC settings.
V2.0 version at https://aws.amazon.com/marketplace/pp/B01CIWY4UO
