### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Robulus77** [SungardAS/enhanced-snapshots#61]
Hello,

I got a question regarding the login to your AMI on AWS.

I used the "mail adress" admin@enhancedsnapshots as described in your documentation and my instance id i-xxxxxxxxxxxxxxxxx as password.

Unfortunately I get a login error when trying to log in.

We can reproduce the problem with creating a second EC2 instance in the account of one of my colleagues.

Can you please give advice on how to log on to the AMI?
I use https://aws-dns to browse the log on screen.

Greetings

Rob

**Comment by rabay108** [comment]
Please see whether you have a IAM role equivalent of es-admin associated with the instance. Otherwise create the es-admin equivalent role as described in the github and use it. That's a prerequisite for the successful launch of the instance

**Comment by Robulus77** [comment]
Hi rabay,

thanks a lot for your help.
We created a complete stack including the IAM role now and AS is woking like a charm now,

Thanks again and greetings!
Rob
