### ISSUE TITLE
Server Destroyed

### ISSUE THREAD

**Issue by NareshDealer** [SungardAS/enhanced-snapshots#86]
Hi,
I have tested few scenarios and it seems to be working in all conditions. However we have some use cases where we are not sure how to proceed, which are listed below:
1: If we delete the snapshot which is created during the process of backup, can application still retrieve the restore from s3 bucket.?
2: If the server is destroyed which means, the whole region goes down. What are the next steps to retrieve backups from the s3 bucket.?
3: Can we update the application in future, which means if v3.0 is released, can we do upgrade or we have to reinstall the whole server.?

Appreciate your time in reading and responding.

Thanks.

**Comment by NareshDealer** [comment]
Any help is really appreciated.

Thanks.

**Comment by iradaik** [comment]
Hello Naresh,

Sorry for the delay with the response. 

1) If backup process was successfully completed you will be able to restore all the data from S3. So you can feel free to remove created snapshots. Also in next version of ESS you will have an option not to store snapshots at all
2) You will have to start new instance with ESS and restore all the data from your S3 bucket. Please refer to README.md file for the details
3) To upgrade system it will be required to start new instance with new version of ESS, you can find description of upgrade process in README.md file as well. No data will be lost after system upgrade.

**Comment by NareshDealer** [comment]
@iradaik  Thank you for kind response.

As per the readme file, there is no mention about dynamo db table details which means can i assume that there is an option to pick existing dynamo db.?

Thanks.

**Comment by iradaik** [comment]
@NareshDealer new tables will be created based on system backup data. 
System backup can be performed from Settings tab. You do not need to backup system every time you create new backup, info about your backups is stored automatically, but you do need to create at least one system backup to be able to migrate to another instance in future

**Comment by NareshDealer** [comment]
@iradaik  Thank you once again, i will check the above use cases and report if i find any issues.

I found some cosmetic bugs, should i share here or create a new issue for it. There are not life ending bugs, but it will be nice if they are also fixed in V3.

Thank you, Excited to see new version with updated features.

**Comment by rabay108** [comment]
Thanks @NareshDealer for your continued feedback and @iradaik for the responses. Please open new issue for the UI related changes.
