### ISSUE TITLE
Tags for Snapshot

### ISSUE THREAD

**Issue by NareshDealer** [SungardAS/enhanced-snapshots#99]
How to store the tags for the snapshot during backup process from the volume. As i have observed the tags are not stored which in turn during the restore process its not assigning the tags for the new volume.

Also it would be good if we can assign the name tag for the snapshot and restored volume from the original volume or assign a name tag or all other tags during the process of snapshot or restore.

Currently its NOT easy to identify the snapshots and restored volumes without the tags.

Thanks.

**Comment by NareshDealer** [comment]
please can someone confirm, if its possible.?

**Comment by iradaik** [comment]
@NareshDealer, unfortunately, we haven't such functionality, for now. We will consider adding it in future releases. Thank you for letting us know how we can improve our application

**Comment by rabay108** [comment]
@NareshDealer We added in the features list for consideration. As a opensource we are also welcoming the community to contribute features. Thanks @iradaik .
